#!/bin/sh
# Generated by releaser â https://github.com/benelser/releaser
# Install releaser on macOS or Linux
set -eu

REPO="benelser/releaser"
BINARY="releaser"
NAME="releaser"
INSTALL_DIR="${HOME}/.local/bin"

main() {
    detect_platform
    fetch_latest_version
    download_and_install
    echo ""
    echo "${BINARY} ${VERSION} installed to ${INSTALL_DIR}/${BINARY}"
    echo ""
    ensure_path
}

detect_platform() {
    OS="$(uname -s)"
    ARCH="$(uname -m)"

    case "${OS}" in
        Darwin) OS="apple-darwin" ;;
        Linux)  OS="unknown-linux-gnu" ;;
        *)      echo "error: unsupported OS: ${OS}"; exit 1 ;;
    esac

    # Detect musl on Linux
    if [ "${OS}" = "unknown-linux-gnu" ]; then
        if ldd --version 2>&1 | grep -q musl; then
            OS="unknown-linux-musl"
        fi
    fi

    case "${ARCH}" in
        x86_64|amd64)   ARCH="x86_64" ;;
        aarch64|arm64)  ARCH="aarch64" ;;
        *)              echo "error: unsupported architecture: ${ARCH}"; exit 1 ;;
    esac

    # Detect Rosetta
    if [ "${OS}" = "apple-darwin" ] && [ "${ARCH}" = "x86_64" ]; then
        if sysctl -n sysctl.proc_translated 2>/dev/null | grep -q 1; then
            ARCH="aarch64"
        fi
    fi

    TARGET="${ARCH}-${OS}"
    echo "detected platform: ${TARGET}"
}

fetch_latest_version() {
    VERSION="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
        | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')"

    if [ -z "${VERSION}" ]; then
        echo "error: could not determine latest version"
        exit 1
    fi
    echo "latest version: ${VERSION}"
}

download_and_install() {
    ARCHIVE="${NAME}-${TARGET}.tar.gz"
    URL="https://github.com/${REPO}/releases/download/${VERSION}/${ARCHIVE}"
    CHECKSUM_URL="${URL}.sha256"

    echo "downloading ${URL}"

    TMPDIR="$(mktemp -d)"
    trap 'rm -rf "${TMPDIR}"' EXIT

    curl -fsSL "${URL}" -o "${TMPDIR}/${ARCHIVE}"
    curl -fsSL "${CHECKSUM_URL}" -o "${TMPDIR}/${ARCHIVE}.sha256"

    # Verify checksum
    cd "${TMPDIR}"
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 -c "${ARCHIVE}.sha256"
    elif command -v sha256sum >/dev/null 2>&1; then
        sha256sum -c "${ARCHIVE}.sha256"
    else
        echo "warning: no checksum tool found, skipping verification"
    fi

    tar xzf "${ARCHIVE}"
    mkdir -p "${INSTALL_DIR}"
    mv "${BINARY}" "${INSTALL_DIR}/${BINARY}"
    chmod +x "${INSTALL_DIR}/${BINARY}"
}

ensure_path() {
    case ":${PATH}:" in
        *":${INSTALL_DIR}:"*) ;;
        *)
            echo "Add ${INSTALL_DIR} to your PATH:"
            echo ""
            echo "  export PATH=\"${INSTALL_DIR}:\$PATH\""
            echo ""
            ;;
    esac
}

main
