# Generated by releaser â https://github.com/benelser/releaser
# Install releaser on Windows
#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$Repo = "benelser/releaser"
$Binary = "releaser"
$Name = "releaser"
$InstallDir = "$env:USERPROFILE\.local\bin"

function Main {
    $Platform = Detect-Platform
    $Version = Fetch-LatestVersion
    Download-And-Install -Platform $Platform -Version $Version
    Ensure-Path
    Write-Host ""
    Write-Host "$Binary $Version installed to $InstallDir\$Binary.exe"
}

function Detect-Platform {
    $Arch = $env:PROCESSOR_ARCHITECTURE
    switch ($Arch) {
        "AMD64" { return "x86_64-pc-windows-msvc" }
        "ARM64" { return "aarch64-pc-windows-msvc" }
        default {
            Write-Error "Unsupported architecture: $Arch"
            exit 1
        }
    }
}

function Fetch-LatestVersion {
    $Release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest"
    return $Release.tag_name
}

function Download-And-Install {
    param($Platform, $Version)

    $Archive = "$Name-$Platform.zip"
    $Url = "https://github.com/$Repo/releases/download/$Version/$Archive"
    $ChecksumUrl = "$Url.sha256"

    Write-Host "Downloading $Url"

    $TmpDir = New-TemporaryFile | ForEach-Object {
        Remove-Item $_
        New-Item -ItemType Directory -Path "$_.dir"
    }

    try {
        Invoke-WebRequest -Uri $Url -OutFile "$TmpDir\$Archive"
        Invoke-WebRequest -Uri $ChecksumUrl -OutFile "$TmpDir\$Archive.sha256"

        # Verify checksum
        $Expected = (Get-Content "$TmpDir\$Archive.sha256").Split(" ")[0]
        $Actual = (Get-FileHash "$TmpDir\$Archive" -Algorithm SHA256).Hash.ToLower()
        if ($Expected -ne $Actual) {
            Write-Error "Checksum mismatch: expected $Expected, got $Actual"
            exit 1
        }

        Expand-Archive -Path "$TmpDir\$Archive" -DestinationPath $TmpDir -Force

        if (-not (Test-Path $InstallDir)) {
            New-Item -ItemType Directory -Path $InstallDir | Out-Null
        }

        Copy-Item "$TmpDir\$Binary.exe" "$InstallDir\$Binary.exe" -Force
    }
    finally {
        Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue
    }
}

function Ensure-Path {
    $UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
    if ($UserPath -notlike "*$InstallDir*") {
        [Environment]::SetEnvironmentVariable("PATH", "$InstallDir;$UserPath", "User")
        Write-Host "Added $InstallDir to your PATH (restart your shell to pick it up)"
    }
}

Main
