use crate::template::{Context, Template};
use super::GenerateContext;

/// Pinned GitHub Action SHAs — tags can be moved, SHAs can't.
struct PinnedAction {
    uses: &'static str,
    sha: &'static str,
    comment: &'static str,
}

const ACTIONS: &[PinnedAction] = &[
    PinnedAction {
        uses: "actions/checkout",
        sha: "34e114876b0b11c390a56381ad16ebd13914f8d5",
        comment: "v4",
    },
    PinnedAction {
        uses: "actions/upload-artifact",
        sha: "ea165f8d65b6e75b540449e92b4886f43607fa02",
        comment: "v4",
    },
    PinnedAction {
        uses: "actions/download-artifact",
        sha: "d3f86a106a0bac45b974a628896c90dbdf5c8093",
        comment: "v4",
    },
    PinnedAction {
        uses: "actions/attest-build-provenance",
        sha: "b3e506e8c389afc651c5bacf2b8f2a1ea0557215",
        comment: "v4",
    },
    PinnedAction {
        uses: "softprops/action-gh-release",
        sha: "153bb8e04406b158c6c84fc1615b65b24149a1fe",
        comment: "v2",
    },
    PinnedAction {
        uses: "PyO3/maturin-action",
        sha: "db323e2cf5679b7feb8bcb561a36b27a0bc19e79",
        comment: "v1",
    },
    PinnedAction {
        uses: "actions/setup-node",
        sha: "49933ea5288caeca8642d1e84afbd3f7d6820020",
        comment: "v4",
    },
];

fn pinned(name: &str) -> String {
    for a in ACTIONS {
        if a.uses == name {
            return format!("{}@{}  # {}", a.uses, a.sha, a.comment);
        }
    }
    format!("{name}@main  # UNPIN: add SHA")
}

pub fn render(gctx: &GenerateContext) -> Result<String, String> {
    let template = Template::new(CI_TEMPLATE);
    let mut ctx = Context::new();

    ctx.set("name", gctx.config.package.name.as_str());
    ctx.set("binary", gctx.config.package.binary.as_str());
    ctx.set("owner", gctx.owner.as_str());
    ctx.set("repo", gctx.repo.as_str());

    // Workspace support: add -p flag if this is a workspace member
    let has_workspace_package = gctx.config.package.workspace_package.is_some();
    ctx.set("has_workspace_package", has_workspace_package);
    if let Some(pkg) = &gctx.config.package.workspace_package {
        ctx.set("cargo_package_flag", format!("-p {pkg}"));
    } else {
        ctx.set("cargo_package_flag", "");
    }

    // Pinned actions
    ctx.set("action_checkout", pinned("actions/checkout"));
    ctx.set("action_upload_artifact", pinned("actions/upload-artifact"));
    ctx.set("action_download_artifact", pinned("actions/download-artifact"));
    ctx.set("action_attest", pinned("actions/attest-build-provenance"));
    ctx.set("action_gh_release", pinned("softprops/action-gh-release"));
    ctx.set("action_maturin", pinned("PyO3/maturin-action"));
    ctx.set("action_setup_node", pinned("actions/setup-node"));

    // Channels
    ctx.set("has_pypi", gctx.config.distribute.pypi.is_some());
    ctx.set("has_npm", gctx.config.distribute.npm.is_some());
    ctx.set("has_cargo", gctx.config.distribute.cargo.is_some());
    ctx.set("has_homebrew", gctx.config.distribute.homebrew.is_some());
    ctx.set("has_scoop", gctx.config.distribute.scoop.is_some());
    // Attestation requires public repos — disable by default, users can enable
    ctx.set("has_attestation", false);

    if let Some(pypi) = &gctx.config.distribute.pypi {
        ctx.set("pypi_package", pypi.package_name.as_str());
    }
    if let Some(npm) = &gctx.config.distribute.npm {
        ctx.set("npm_scope", npm.scope.as_str());
    }
    if let Some(homebrew) = &gctx.config.distribute.homebrew {
        ctx.set("homebrew_tap", homebrew.tap.as_str());
    }
    if let Some(scoop) = &gctx.config.distribute.scoop {
        ctx.set("scoop_bucket", scoop.bucket.as_str());
    }

    // Targets
    let targets: Vec<Context> = gctx.config.targets.platforms.iter().map(|t| {
        let mut c = Context::new();
        c.set("triple", t.as_str());
        c.set("os", t.os());
        c.set("arch", t.arch());
        c.set("runner", t.github_runner());
        c.set("archive_ext", t.archive_extension());
        c.set("binary_ext", t.binary_extension());
        c.set("is_windows", t.os() == "windows");
        c.set("is_musl", t.is_musl());
        c.set("npm_os", t.npm_os());
        c.set("npm_cpu", t.npm_cpu());
        c
    }).collect();
    ctx.set_list("targets", targets);

    template.render(&ctx).map_err(|e| e.to_string())
}

const CI_TEMPLATE: &str = r#"# Generated by bincast - do not edit manually
# https://github.com/benelser/bincast
name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write
  id-token: write
  attestations: write

jobs:
  build:
    name: Build (${{ matrix.target }})
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
{% for t in targets %}          - target: {{ t.triple }}
            runner: {{ t.runner }}
{% endfor %}
    steps:
      - uses: {{ action_checkout }}

      - name: Install Rust toolchain
        run: |
          rustup toolchain install stable --profile minimal
          rustup target add ${{ matrix.target }}

      - name: Install cross-compilation tools
        if: runner.os == 'Linux'
        shell: bash
        run: |
          sudo apt-get update -q
          case "${{ matrix.target }}" in
            aarch64-unknown-linux-gnu)
              sudo apt-get install -yq gcc-aarch64-linux-gnu
              echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_GNU_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              ;;
            aarch64-unknown-linux-musl)
              sudo apt-get install -yq gcc-aarch64-linux-gnu musl-tools
              echo "CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER=aarch64-linux-gnu-gcc" >> $GITHUB_ENV
              ;;
            x86_64-unknown-linux-musl)
              sudo apt-get install -yq musl-tools
              ;;
          esac

      - name: Build binary
        run: cargo build --release --target ${{ matrix.target }} {{ cargo_package_flag }}

      - name: Create archive
        shell: bash
        run: |
          cd target/${{ matrix.target }}/release
          if [[ "${{ matrix.target }}" == *"windows"* ]]; then
            7z a ../../../{{ name }}-${{ matrix.target }}.zip {{ binary }}.exe
          else
            tar czf ../../../{{ name }}-${{ matrix.target }}.tar.gz {{ binary }}
          fi
{% if has_pypi %}
      - name: Transform README for PyPI
        shell: bash
        run: |
          if [ -f README.md ]; then
            # Strip <picture>, <source>, <details>, <summary> tags for PyPI compatibility
            sed -e 's/<picture[^>]*>//g' -e 's/<\/picture>//g' \
                -e 's/<source[^>]*>//g' -e 's/<\/source>//g' \
                -e 's/<details[^>]*>//g' -e 's/<\/details>//g' \
                -e 's/<summary[^>]*>//g' -e 's/<\/summary>//g' \
                README.md > README.pypi.md
          fi

      - name: Build maturin wheel
        uses: {{ action_maturin }}
        with:
          target: ${{ matrix.target }}
          args: --release --bindings bin --strip
          manylinux: auto
{% endif %}
      - name: Compute SHA-256
        shell: bash
        run: |
          shopt -s nullglob
          for f in {{ name }}-${{ matrix.target }}.* target/wheels/*.whl; do
            if [ -f "$f" ]; then
              sha256sum "$f" > "$f.sha256" 2>/dev/null || shasum -a 256 "$f" > "$f.sha256"
            fi
          done

      - name: Smoke test
        if: |
          runner.os != 'Windows' &&
          !(runner.arch == 'X64' && contains(matrix.target, 'aarch64'))
        run: |
          target/${{ matrix.target }}/release/{{ binary }} --help

      - uses: {{ action_upload_artifact }}
        with:
          name: archive-${{ matrix.target }}
          path: |
            {{ name }}-${{ matrix.target }}.*
{% if has_pypi %}
      - uses: {{ action_upload_artifact }}
        with:
          name: wheels-${{ matrix.target }}
          path: target/wheels/*.whl
{% endif %}
  release:
    name: GitHub Release
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: {{ action_checkout }}

      - uses: {{ action_download_artifact }}
        with:
          pattern: archive-*
          path: artifacts
          merge-multiple: true

{% if has_attestation %}      - uses: {{ action_attest }}
        with:
          subject-path: "artifacts/*"
{% endif %}
      - uses: {{ action_gh_release }}
        with:
          files: artifacts/*
          generate_release_notes: true
{% if has_pypi %}
  publish-pypi:
    name: Publish to PyPI
    needs: [build]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/project/{{ pypi_package }}
    permissions:
      id-token: write
    steps:
      - uses: {{ action_download_artifact }}
        with:
          pattern: wheels-*
          path: dist
          merge-multiple: true

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: dist/
{% endif %}{% if has_npm %}
  publish-npm:
    name: Publish to npm
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: {{ action_checkout }}

      - uses: {{ action_download_artifact }}
        with:
          pattern: archive-*
          path: artifacts
          merge-multiple: true

      - name: Setup Node.js
        uses: {{ action_setup_node }}
        with:
          node-version: "22"
          registry-url: "https://registry.npmjs.org"

      - name: Publish platform packages
        shell: bash
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          VERSION="${GITHUB_REF_NAME#v}"
{% for t in targets %}          mkdir -p npm-{{ t.npm_os }}-{{ t.npm_cpu }}/bin
          if [[ -f "artifacts/{{ name }}-{{ t.triple }}.tar.gz" ]]; then
            tar xzf "artifacts/{{ name }}-{{ t.triple }}.tar.gz" -C "npm-{{ t.npm_os }}-{{ t.npm_cpu }}/bin/"
          elif [[ -f "artifacts/{{ name }}-{{ t.triple }}.zip" ]]; then
            unzip -o "artifacts/{{ name }}-{{ t.triple }}.zip" -d "npm-{{ t.npm_os }}-{{ t.npm_cpu }}/bin/"
          fi
          cat > "npm-{{ t.npm_os }}-{{ t.npm_cpu }}/package.json" << PKGJSON
          {"name":"{{ npm_scope }}/{{ binary }}-{{ t.npm_os }}-{{ t.npm_cpu }}","version":"${VERSION}","os":["{{ t.npm_os }}"],"cpu":["{{ t.npm_cpu }}"],"bin":{"{{ binary }}":"bin/{{ binary }}{{ t.binary_ext }}"},"preferUnplugged":true}
          PKGJSON
          cd "npm-{{ t.npm_os }}-{{ t.npm_cpu }}" && npm publish --provenance --access public && cd ..
{% endfor %}
{% endif %}{% if has_cargo %}
  publish-crates:
    name: Publish to crates.io
    needs: [release]
    runs-on: ubuntu-latest
    permissions:
      id-token: write
    steps:
      - uses: {{ action_checkout }}

      - name: Install Rust toolchain
        run: rustup toolchain install stable --profile minimal

      - name: Publish to crates.io
        run: cargo publish {{ cargo_package_flag }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
{% endif %}{% if has_homebrew %}
  dispatch-homebrew:
    name: Update Homebrew tap
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to tap repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.TAP_GITHUB_TOKEN }}
          repository: {{ homebrew_tap }}
          event-type: update-formula
          client-payload: '{"version": "${{ github.ref_name }}"}'
{% endif %}{% if has_scoop %}
  dispatch-scoop:
    name: Update Scoop bucket
    needs: [release]
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch to bucket repo
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.BUCKET_GITHUB_TOKEN }}
          repository: {{ scoop_bucket }}
          event-type: update-manifest
          client-payload: '{"version": "${{ github.ref_name }}"}'
{% endif %}"#;
