use crate::template::{Context, Template};
use super::GenerateContext;

pub fn render(gctx: &GenerateContext) -> Result<String, String> {
    let template = Template::new(HOMEBREW_TEMPLATE);
    let mut ctx = Context::new();

    ctx.set("name", gctx.config.package.name.as_str());
    ctx.set("binary", gctx.config.package.binary.as_str());
    ctx.set("owner", gctx.owner.as_str());
    ctx.set("repo", gctx.repo.as_str());

    let desc = gctx.config.package.description.as_deref().unwrap_or("");
    ctx.set("description", desc);

    let license = gctx.config.package.license.as_deref().unwrap_or("MIT");
    ctx.set("license", license);

    let homepage = gctx.config.package.homepage.as_deref()
        .unwrap_or(&gctx.config.package.repository);
    ctx.set("homepage", homepage);

    // Build class name: capitalize first letter of each word
    let class_name = to_class_name(&gctx.config.package.name);
    ctx.set("class_name", class_name);

    // Targets for platform blocks
    let has_macos_arm = gctx.config.targets.platforms.iter().any(|t| t.as_str() == "aarch64-apple-darwin");
    let has_macos_x86 = gctx.config.targets.platforms.iter().any(|t| t.as_str() == "x86_64-apple-darwin");
    let has_linux_arm = gctx.config.targets.platforms.iter().any(|t| t.as_str() == "aarch64-unknown-linux-gnu");
    let has_linux_x86 = gctx.config.targets.platforms.iter().any(|t| t.as_str() == "x86_64-unknown-linux-gnu");

    ctx.set("has_macos_arm", has_macos_arm);
    ctx.set("has_macos_x86", has_macos_x86);
    ctx.set("has_linux_arm", has_linux_arm);
    ctx.set("has_linux_x86", has_linux_x86);

    template.render(&ctx)
}

fn to_class_name(name: &str) -> String {
    name.split(['-', '_'])
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(first) => {
                    let mut s = first.to_uppercase().to_string();
                    s.extend(chars);
                    s
                }
            }
        })
        .collect()
}

const HOMEBREW_TEMPLATE: &str = r##"# Generated by bincast - https://github.com/benelser/bincast
# Homebrew formula for {{ name }}
class {{ class_name }} < Formula
  desc "{{ description }}"
  homepage "{{ homepage }}"
  license "{{ license }}"

{% if has_macos_arm %}  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/{{ owner }}/{{ repo }}/releases/download/v#{version}/{{ name }}-aarch64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
{% if has_macos_x86 %}    if Hardware::CPU.intel?
      url "https://github.com/{{ owner }}/{{ repo }}/releases/download/v#{version}/{{ name }}-x86_64-apple-darwin.tar.gz"
      sha256 "PLACEHOLDER"
    end
{% endif %}  end
{% endif %}
{% if has_linux_arm %}  on_linux do
    if Hardware::CPU.arm?
      url "https://github.com/{{ owner }}/{{ repo }}/releases/download/v#{version}/{{ name }}-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
{% if has_linux_x86 %}    if Hardware::CPU.intel?
      url "https://github.com/{{ owner }}/{{ repo }}/releases/download/v#{version}/{{ name }}-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "PLACEHOLDER"
    end
{% endif %}  end
{% endif %}
  def install
    bin.install "{{ binary }}"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/{{ binary }} --version")
  end
end
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_to_class_name() {
        assert_eq!(to_class_name("durable"), "Durable");
        assert_eq!(to_class_name("my-tool"), "MyTool");
        assert_eq!(to_class_name("my_cool_tool"), "MyCoolTool");
    }
}
