use crate::template::{Context, Template};
use super::GenerateContext;

pub fn render_sh(gctx: &GenerateContext) -> Result<String, String> {
    let template = Template::new(INSTALL_SH_TEMPLATE);
    let mut ctx = Context::new();
    ctx.set("name", gctx.config.package.name.as_str());
    ctx.set("binary", gctx.config.package.binary.as_str());
    ctx.set("owner", gctx.owner.as_str());
    ctx.set("repo", gctx.repo.as_str());
    template.render(&ctx)
}

pub fn render_ps1(gctx: &GenerateContext) -> Result<String, String> {
    let template = Template::new(INSTALL_PS1_TEMPLATE);
    let mut ctx = Context::new();
    ctx.set("name", gctx.config.package.name.as_str());
    ctx.set("binary", gctx.config.package.binary.as_str());
    ctx.set("owner", gctx.owner.as_str());
    ctx.set("repo", gctx.repo.as_str());
    template.render(&ctx)
}

const INSTALL_SH_TEMPLATE: &str = r#"#!/bin/sh
# Generated by bincast — https://github.com/benelser/bincast
# Install {{ name }} on macOS or Linux
set -eu

REPO="{{ owner }}/{{ repo }}"
BINARY="{{ binary }}"
NAME="{{ name }}"
INSTALL_DIR="${HOME}/.local/bin"

main() {
    detect_platform
    fetch_latest_version
    download_and_install
    echo ""
    echo "${BINARY} ${VERSION} installed to ${INSTALL_DIR}/${BINARY}"
    echo ""
    ensure_path
}

detect_platform() {
    OS="$(uname -s)"
    ARCH="$(uname -m)"

    case "${OS}" in
        Darwin) OS="apple-darwin" ;;
        Linux)  OS="unknown-linux-gnu" ;;
        *)      echo "error: unsupported OS: ${OS}"; exit 1 ;;
    esac

    # Detect musl on Linux
    if [ "${OS}" = "unknown-linux-gnu" ]; then
        if ldd --version 2>&1 | grep -q musl; then
            OS="unknown-linux-musl"
        fi
    fi

    case "${ARCH}" in
        x86_64|amd64)   ARCH="x86_64" ;;
        aarch64|arm64)  ARCH="aarch64" ;;
        *)              echo "error: unsupported architecture: ${ARCH}"; exit 1 ;;
    esac

    # Detect Rosetta
    if [ "${OS}" = "apple-darwin" ] && [ "${ARCH}" = "x86_64" ]; then
        if sysctl -n sysctl.proc_translated 2>/dev/null | grep -q 1; then
            ARCH="aarch64"
        fi
    fi

    TARGET="${ARCH}-${OS}"
    echo "detected platform: ${TARGET}"
}

fetch_latest_version() {
    VERSION="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
        | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')"

    if [ -z "${VERSION}" ]; then
        echo "error: could not determine latest version"
        exit 1
    fi
    echo "latest version: ${VERSION}"
}

download_and_install() {
    ARCHIVE="${NAME}-${TARGET}.tar.gz"
    URL="https://github.com/${REPO}/releases/download/${VERSION}/${ARCHIVE}"
    CHECKSUM_URL="${URL}.sha256"

    echo "downloading ${URL}"

    TMPDIR="$(mktemp -d)"
    trap 'rm -rf "${TMPDIR}"' EXIT

    curl -fsSL "${URL}" -o "${TMPDIR}/${ARCHIVE}"
    curl -fsSL "${CHECKSUM_URL}" -o "${TMPDIR}/${ARCHIVE}.sha256"

    # Verify checksum
    cd "${TMPDIR}"
    if command -v shasum >/dev/null 2>&1; then
        shasum -a 256 -c "${ARCHIVE}.sha256"
    elif command -v sha256sum >/dev/null 2>&1; then
        sha256sum -c "${ARCHIVE}.sha256"
    else
        echo "warning: no checksum tool found, skipping verification"
    fi

    tar xzf "${ARCHIVE}"
    mkdir -p "${INSTALL_DIR}"
    mv "${BINARY}" "${INSTALL_DIR}/${BINARY}"
    chmod +x "${INSTALL_DIR}/${BINARY}"
}

ensure_path() {
    case ":${PATH}:" in
        *":${INSTALL_DIR}:"*) ;;
        *)
            echo "Add ${INSTALL_DIR} to your PATH:"
            echo ""
            echo "  export PATH=\"${INSTALL_DIR}:\$PATH\""
            echo ""
            ;;
    esac
}

main
"#;

const INSTALL_PS1_TEMPLATE: &str = r#"# Generated by bincast — https://github.com/benelser/bincast
# Install {{ name }} on Windows
#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$Repo = "{{ owner }}/{{ repo }}"
$Binary = "{{ binary }}"
$Name = "{{ name }}"
$InstallDir = "$env:USERPROFILE\.local\bin"

function Main {
    $Platform = Detect-Platform
    $Version = Fetch-LatestVersion
    Download-And-Install -Platform $Platform -Version $Version
    Ensure-Path
    Write-Host ""
    Write-Host "$Binary $Version installed to $InstallDir\$Binary.exe"
}

function Detect-Platform {
    $Arch = $env:PROCESSOR_ARCHITECTURE
    switch ($Arch) {
        "AMD64" { return "x86_64-pc-windows-msvc" }
        "ARM64" { return "aarch64-pc-windows-msvc" }
        default {
            Write-Error "Unsupported architecture: $Arch"
            exit 1
        }
    }
}

function Fetch-LatestVersion {
    $Release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest"
    return $Release.tag_name
}

function Download-And-Install {
    param($Platform, $Version)

    $Archive = "$Name-$Platform.zip"
    $Url = "https://github.com/$Repo/releases/download/$Version/$Archive"
    $ChecksumUrl = "$Url.sha256"

    Write-Host "Downloading $Url"

    $TmpDir = New-TemporaryFile | ForEach-Object {
        Remove-Item $_
        New-Item -ItemType Directory -Path "$_.dir"
    }

    try {
        Invoke-WebRequest -Uri $Url -OutFile "$TmpDir\$Archive"
        Invoke-WebRequest -Uri $ChecksumUrl -OutFile "$TmpDir\$Archive.sha256"

        # Verify checksum
        $Expected = (Get-Content "$TmpDir\$Archive.sha256").Split(" ")[0]
        $Actual = (Get-FileHash "$TmpDir\$Archive" -Algorithm SHA256).Hash.ToLower()
        if ($Expected -ne $Actual) {
            Write-Error "Checksum mismatch: expected $Expected, got $Actual"
            exit 1
        }

        Expand-Archive -Path "$TmpDir\$Archive" -DestinationPath $TmpDir -Force

        if (-not (Test-Path $InstallDir)) {
            New-Item -ItemType Directory -Path $InstallDir | Out-Null
        }

        Copy-Item "$TmpDir\$Binary.exe" "$InstallDir\$Binary.exe" -Force
    }
    finally {
        Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue
    }
}

function Ensure-Path {
    $UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
    if ($UserPath -notlike "*$InstallDir*") {
        [Environment]::SetEnvironmentVariable("PATH", "$InstallDir;$UserPath", "User")
        Write-Host "Added $InstallDir to your PATH (restart your shell to pick it up)"
    }
}

Main
"#;
