use crate::template::{Context, Template};
use super::GenerateContext;

pub fn render_sh(gctx: &GenerateContext) -> Result<String, String> {
    let template = Template::new(INSTALL_SH_TEMPLATE);
    let mut ctx = Context::new();
    ctx.set("name", gctx.config.package.name.as_str());
    ctx.set("binary", gctx.config.package.binary.as_str());
    ctx.set("owner", gctx.owner.as_str());
    ctx.set("repo", gctx.repo.as_str());
    template.render(&ctx)
}

pub fn render_ps1(gctx: &GenerateContext) -> Result<String, String> {
    let template = Template::new(INSTALL_PS1_TEMPLATE);
    let mut ctx = Context::new();
    ctx.set("name", gctx.config.package.name.as_str());
    ctx.set("binary", gctx.config.package.binary.as_str());
    ctx.set("owner", gctx.owner.as_str());
    ctx.set("repo", gctx.repo.as_str());
    template.render(&ctx)
}

const INSTALL_SH_TEMPLATE: &str = r#"#!/bin/sh
# Generated by bincast — https://github.com/benelser/bincast
# Install {{ name }} on macOS or Linux
set -eu

REPO="{{ owner }}/{{ repo }}"
BINARY="{{ binary }}"
NAME="{{ name }}"
INSTALL_DIR="${HOME}/.local/bin"

main() {
    detect_platform
    fetch_latest_version
    download_and_install
    echo ""
    echo "${BINARY} ${VERSION} installed to ${INSTALL_DIR}/${BINARY}"
    echo ""
    ensure_path
}

detect_platform() {
    OS="$(uname -s)"
    ARCH="$(uname -m)"

    case "${OS}" in
        Darwin) OS="apple-darwin" ;;
        Linux)  OS="unknown-linux-gnu" ;;
        *)      echo "error: unsupported OS: ${OS}"; exit 1 ;;
    esac

    # Detect musl on Linux
    if [ "${OS}" = "unknown-linux-gnu" ]; then
        if ldd --version 2>&1 | grep -q musl; then
            OS="unknown-linux-musl"
        fi
    fi

    case "${ARCH}" in
        x86_64|amd64)   ARCH="x86_64" ;;
        aarch64|arm64)  ARCH="aarch64" ;;
        *)              echo "error: unsupported architecture: ${ARCH}"; exit 1 ;;
    esac

    # Detect Rosetta
    if [ "${OS}" = "apple-darwin" ] && [ "${ARCH}" = "x86_64" ]; then
        if sysctl -n sysctl.proc_translated 2>/dev/null | grep -q 1; then
            ARCH="aarch64"
        fi
    fi

    TARGET="${ARCH}-${OS}"
    echo "detected platform: ${TARGET}"
}

fetch_latest_version() {
    if command -v gh >/dev/null 2>&1; then
        VERSION="$(gh release view --repo "${REPO}" --json tagName --jq .tagName 2>/dev/null)"
    fi
    if [ -z "${VERSION}" ]; then
        VERSION="$(curl -fsSL "https://api.github.com/repos/${REPO}/releases/latest" \
            | grep '"tag_name"' | head -1 | sed 's/.*"tag_name": *"\([^"]*\)".*/\1/')"
    fi

    if [ -z "${VERSION}" ]; then
        echo "error: could not determine latest version"
        echo "  If this is a private repo, install gh: https://cli.github.com/"
        exit 1
    fi
    echo "latest version: ${VERSION}"
}

download_and_install() {
    ARCHIVE="${NAME}-${TARGET}.tar.gz"

    TMPDIR="$(mktemp -d)"
    trap 'rm -rf "${TMPDIR}"' EXIT

    # Download using gh if available (supports private repos), else curl
    if command -v gh >/dev/null 2>&1; then
        echo "downloading ${ARCHIVE} via gh..."
        gh release download "${VERSION}" --repo "${REPO}" \
            --pattern "${ARCHIVE}" --pattern "${ARCHIVE}.sha256" \
            --dir "${TMPDIR}" 2>/dev/null
    fi

    # Fallback to curl if gh didn't work or isn't installed
    if [ ! -f "${TMPDIR}/${ARCHIVE}" ]; then
        URL="https://github.com/${REPO}/releases/download/${VERSION}/${ARCHIVE}"
        echo "downloading ${URL}"
        curl -fsSL "${URL}" -o "${TMPDIR}/${ARCHIVE}"
        curl -fsSL "${URL}.sha256" -o "${TMPDIR}/${ARCHIVE}.sha256" 2>/dev/null || true
    fi

    # Verify checksum if sidecar exists
    cd "${TMPDIR}"
    if [ -f "${ARCHIVE}.sha256" ]; then
        if command -v sha256sum >/dev/null 2>&1; then
            sha256sum -c "${ARCHIVE}.sha256"
        elif command -v shasum >/dev/null 2>&1; then
            shasum -a 256 -c "${ARCHIVE}.sha256"
        fi
    fi

    tar xzf "${ARCHIVE}"
    mkdir -p "${INSTALL_DIR}"
    mv "${BINARY}" "${INSTALL_DIR}/${BINARY}"
    chmod +x "${INSTALL_DIR}/${BINARY}"
}

ensure_path() {
    case ":${PATH}:" in
        *":${INSTALL_DIR}:"*) ;;
        *)
            echo "Add ${INSTALL_DIR} to your PATH:"
            echo ""
            echo "  export PATH=\"${INSTALL_DIR}:\$PATH\""
            echo ""
            ;;
    esac
}

main
"#;

const INSTALL_PS1_TEMPLATE: &str = r#"# Generated by bincast — https://github.com/benelser/bincast
# Install {{ name }} on Windows
#Requires -Version 5.1
$ErrorActionPreference = "Stop"

$Repo = "{{ owner }}/{{ repo }}"
$Binary = "{{ binary }}"
$Name = "{{ name }}"
$InstallDir = "$env:USERPROFILE\.local\bin"

function Main {
    $Platform = Detect-Platform
    $Version = Fetch-LatestVersion
    Download-And-Install -Platform $Platform -Version $Version
    Ensure-Path
    Write-Host ""
    Write-Host "$Binary $Version installed to $InstallDir\$Binary.exe"
}

function Detect-Platform {
    $Arch = $env:PROCESSOR_ARCHITECTURE
    switch ($Arch) {
        "AMD64" { return "x86_64-pc-windows-msvc" }
        "ARM64" { return "aarch64-pc-windows-msvc" }
        default {
            Write-Error "Unsupported architecture: $Arch"
            exit 1
        }
    }
}

function Fetch-LatestVersion {
    # Try gh CLI first (works for private repos)
    try {
        $version = & gh release view --repo $Repo --json tagName --jq .tagName 2>$null
        if ($version) { return $version }
    } catch {}
    # Fallback to API
    $Release = Invoke-RestMethod -Uri "https://api.github.com/repos/$Repo/releases/latest"
    return $Release.tag_name
}

function Download-And-Install {
    param($Platform, $Version)

    $Archive = "$Name-$Platform.zip"

    # Try gh CLI first (supports private repos)
    $downloaded = $false
    try {
        & gh release download $Version --repo $Repo --pattern $Archive --pattern "$Archive.sha256" --dir $env:TEMP 2>$null
        if (Test-Path "$env:TEMP\$Archive") { $downloaded = $true }
    } catch {}

    $TmpDir = New-TemporaryFile | ForEach-Object {
        Remove-Item $_
        New-Item -ItemType Directory -Path "$_.dir"
    }

    try {
        if (-not $downloaded) {
            $Url = "https://github.com/$Repo/releases/download/$Version/$Archive"
            Write-Host "Downloading $Url"
            Invoke-WebRequest -Uri $Url -OutFile "$TmpDir\$Archive"
            Invoke-WebRequest -Uri "$Url.sha256" -OutFile "$TmpDir\$Archive.sha256" -ErrorAction SilentlyContinue
        } else {
            Move-Item "$env:TEMP\$Archive" "$TmpDir\$Archive"
            if (Test-Path "$env:TEMP\$Archive.sha256") {
                Move-Item "$env:TEMP\$Archive.sha256" "$TmpDir\$Archive.sha256"
            }
        }

        # Verify checksum if available
        if (Test-Path "$TmpDir\$Archive.sha256") {
            $Expected = (Get-Content "$TmpDir\$Archive.sha256").Split(" ")[0]
            $Actual = (Get-FileHash "$TmpDir\$Archive" -Algorithm SHA256).Hash.ToLower()
            if ($Expected -ne $Actual) {
                Write-Error "Checksum mismatch: expected $Expected, got $Actual"
                exit 1
            }
        }

        Expand-Archive -Path "$TmpDir\$Archive" -DestinationPath $TmpDir -Force

        if (-not (Test-Path $InstallDir)) {
            New-Item -ItemType Directory -Path $InstallDir | Out-Null
        }

        Copy-Item "$TmpDir\$Binary.exe" "$InstallDir\$Binary.exe" -Force
    }
    finally {
        Remove-Item -Recurse -Force $TmpDir -ErrorAction SilentlyContinue
    }
}

function Ensure-Path {
    $UserPath = [Environment]::GetEnvironmentVariable("PATH", "User")
    if ($UserPath -notlike "*$InstallDir*") {
        [Environment]::SetEnvironmentVariable("PATH", "$InstallDir;$UserPath", "User")
        Write-Host "Added $InstallDir to your PATH (restart your shell to pick it up)"
    }
}

Main
"#;
