//! Generates receiver workflows for Homebrew tap and Scoop bucket repos.
//! These workflows run when the main repo dispatches a repository event
//! with the new version and checksums.

use crate::template::{Context, Template};

/// Generate the receiver workflow for a Homebrew tap repo.
pub fn homebrew_receiver_workflow(
    name: &str,
    binary: &str,
    owner: &str,
    repo: &str,
) -> Result<String, String> {
    let template = Template::new(HOMEBREW_RECEIVER);
    let mut ctx = Context::new();
    ctx.set("name", name);
    ctx.set("binary", binary);
    ctx.set("owner", owner);
    ctx.set("repo", repo);
    template.render(&ctx)
}

/// Generate the receiver workflow for a Scoop bucket repo.
pub fn scoop_receiver_workflow(
    name: &str,
    owner: &str,
    repo: &str,
) -> Result<String, String> {
    let template = Template::new(SCOOP_RECEIVER);
    let mut ctx = Context::new();
    ctx.set("name", name);
    ctx.set("owner", owner);
    ctx.set("repo", repo);
    template.render(&ctx)
}

const HOMEBREW_RECEIVER: &str = r##"# Generated by releaser — https://github.com/benelser/releaser
# Place this in .github/workflows/update-formula.yml in your Homebrew tap repo.
name: Update Formula

on:
  repository_dispatch:
    types: [update-formula]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

      - name: Update formula
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          # Strip leading 'v' from version
          VER="${VERSION#v}"

          # Download checksums from the release
          for target in aarch64-apple-darwin x86_64-apple-darwin aarch64-unknown-linux-gnu x86_64-unknown-linux-gnu; do
            URL="https://github.com/{{ owner }}/{{ repo }}/releases/download/${VERSION}/{{ name }}-${target}.tar.gz.sha256"
            SHA=$(curl -fsSL "$URL" | awk '{print $1}')
            # Replace PLACEHOLDER or old SHA for this target in the formula
            sed -i "/${target}/{ n; s/sha256 \"[a-f0-9]*\"/sha256 \"${SHA}\"/; }" Formula/{{ name }}.rb
          done

          # Update version
          sed -i "s/version \"[^\"]*\"/version \"${VER}\"/" Formula/{{ name }}.rb

      - name: Commit and push
        run: |
          git config user.name "releaser[bot]"
          git config user.email "releaser[bot]@users.noreply.github.com"
          git add Formula/{{ name }}.rb
          git commit -m "{{ name }} ${VERSION}"
          git push
"##;

const SCOOP_RECEIVER: &str = r#"# Generated by releaser — https://github.com/benelser/releaser
# Place this in .github/workflows/update-manifest.yml in your Scoop bucket repo.
name: Update Manifest

on:
  repository_dispatch:
    types: [update-manifest]

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4

      - name: Update manifest
        env:
          VERSION: ${{ github.event.client_payload.version }}
        run: |
          VER="${VERSION#v}"

          # Download checksum
          URL="https://github.com/{{ owner }}/{{ repo }}/releases/download/${VERSION}/{{ name }}-x86_64-pc-windows-msvc.zip.sha256"
          SHA=$(curl -fsSL "$URL" | awk '{print $1}')

          # Update version and hash in manifest
          jq --arg ver "$VER" --arg sha "$SHA" \
            '.version = $ver | .architecture["64bit"].hash = $sha | .architecture["64bit"].url = (.architecture["64bit"].url | gsub("v[0-9.]+"; "v" + $ver))' \
            bucket/{{ name }}.json > tmp.json && mv tmp.json bucket/{{ name }}.json

      - name: Commit and push
        run: |
          git config user.name "releaser[bot]"
          git config user.email "releaser[bot]@users.noreply.github.com"
          git add bucket/{{ name }}.json
          git commit -m "{{ name }} ${VERSION}"
          git push
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_homebrew_receiver_contains_expected_elements() {
        let output = homebrew_receiver_workflow("my-tool", "my-tool", "user", "my-tool").unwrap();
        assert!(output.contains("repository_dispatch"));
        assert!(output.contains("update-formula"));
        assert!(output.contains("Formula/my-tool.rb"));
        assert!(output.contains("user/my-tool/releases"));
        assert!(output.contains("releaser[bot]"));
    }

    #[test]
    fn test_scoop_receiver_contains_expected_elements() {
        let output = scoop_receiver_workflow("my-tool", "user", "my-tool").unwrap();
        assert!(output.contains("repository_dispatch"));
        assert!(output.contains("update-manifest"));
        assert!(output.contains("bucket/my-tool.json"));
        assert!(output.contains("x86_64-pc-windows-msvc"));
    }
}
